import {
  Layout,
  Server,
  Database,
  Wrench,
  Layers,
  Globe,
  LayoutDashboard,
  Box,
  GraduationCap,
  HeartPulse,
  Users,
  ShoppingCart,
  Contact,
  Network,
  Code2,
  ShieldCheck,
  Gauge,
  Smartphone,
  Rocket,
  Brain,
  Bot,
  Sparkles,
  CloudRain,
  TrendingUp,
  Cpu,
  ExternalLink,
  Code,
  Clock,
  Briefcase,
} from "lucide-react";

const ICON_MAP = {
  layout: Layout,
  server: Server,
  database: Database,
  wrench: Wrench,
  layers: Layers,
  stack: Layers,
  globe: Globe,
  dashboard: LayoutDashboard,
  box: Box,
  graduation: GraduationCap,
  heart: HeartPulse,
  users: Users,
  cart: ShoppingCart,
  contact: Contact,
  network: Network,
  api: Code2,
  shield: ShieldCheck,
  gauge: Gauge,
  devices: Smartphone,
  mobile: Smartphone,
  smartphone: Smartphone,
  rocket: Rocket,
  brain: Brain,
  ai: Brain,
  bot: Bot,
  sparkles: Sparkles,
  weather: CloudRain,
  analytics: TrendingUp,
  cpu: Cpu,
  link: ExternalLink,
  code: Code,
  clock: Clock,
  briefcase: Briefcase,
};

export function getIcon(name) {
  return ICON_MAP[name] ?? Layout;
}
